# DO NOT create top level (global) keys like env, arch, os, compiler.
# The top level/global keys invoke [unwanted] matrix expansion. Also
# see https://stackoverflow.com/q/58473000/608639 and
# https://docs.travis-ci.com/user/reference/overview/ and
# https://docs.travis-ci.com/user/multi-cpu-architectures and
# https://github.com/travis-ci/travis-yml/blob/master/schema.json.

language: cpp
dist: bionic

git:
  depth: 2

# Use jobs rather than matrix since we are precisely
# specifiying our test cases. Do not move any of the
# keys (env, os, arch, compiler, etc) into global.
# Putting them in global invokes the matrix expansion.
jobs:
  include:
    - os: linux
      name: Linux, amd64, GCC
      arch: amd64
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, amd64, Clang
      arch: amd64
      compiler: clang
      dist: bionic
    - os: linux
      name: Linux, arm64, GCC
      arch: arm64
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, arm64, Clang
      arch: arm64
      compiler: clang
      dist: bionic
    - os: linux
      name: Linux, ppc64le, GCC
      arch: ppc64le
      compiler: gcc
      dist: bionic
    - os: linux
      name: Linux, ppc64le, Clang
      arch: ppc64le
      compiler: clang
      dist: bionic
    - os: osx
      name: OS X, amd64, GCC
      arch: amd64
      compiler: gcc
    - os: osx
      name: OS X, amd64, Clang
      arch: amd64
      compiler: clang

  allow_failures:
    # OS X still supplies OpenSSL 0.9.8 or 1.0.0. The ancient
    # OpenSSL is too old for the PEM key generation routines.
    - os: osx

before_script:
    # Let travis clone cryptopp-pem, clone cryptopp
    # copy cryptopp-pem to cryptopp, and then run
    # the test script.
  - |
    cd ..
    git clone https://github.com/weidai11/cryptopp.git
    cp cryptopp-pem/*.* cryptopp/
    cd cryptopp
    cp TestScripts/cryptest-pem.sh .

script:
  - |    
    bash cryptest-pem.sh

# Whitelist branches to avoid testing feature branches twice
branches:
  only:
    - master
    - /\/ci$/

notifications:
  email:
    recipients:
      - cryptopp-build@googlegroups.com
    on_success: always # default: change
    on_failure: always # default: always
